### ISSUE TITLE
希望增加 古籍印刷通用字規範字形表轉換標準 感謝作者

### ISSUE THREAD

**Issue by jisbig5** [thisObedience/OpenCC-GUI#2]
感謝作者 終於有圖形介面轉換open cc 了 希望增加繁體轉換標準

繁簡轉換之《古籍印刷通用字規範字形表》標準
網址:https://github.com/forFudan/GujiCC

**Comment by ilvon** [comment]
已添加 [(v1.1.2)](https://github.com/ilvon/OpenCC-GUI/releases/tag/v1.1.2)
